import type { Metadata } from "next";
import { NextIntlClientProvider } from 'next-intl';
import { getLocale, getMessages } from 'next-intl/server';
import { Analytics } from "@vercel/analytics/react";
import "./globals.css";
import { ReactScan } from "~/components/ReactScan";
import localFont from 'next/font/local'

const inter = localFont({
  src: '../fonts/Inter.ttf',
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  const locale = await getLocale();
  const messages = await getMessages();

  return (
    <html lang={locale} className={inter.className}>
      <body className="antialiased">
        <NextIntlClientProvider messages={messages}>
          <ReactScan />
          {children}
          <Analytics />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
